Added feature to open tabs in new window
osdc/TabuRei pull request #51
Opened 2021-06-21 20:57 UTC by PrimalPimmy

Fixes #44 , use middle click on restore button.

Gif below shows first opening tabs in new window and the default click to open tabs in the current window afterwards to show the difference. 
![ezgif-2-977836ccf20b](https://user-images.githubusercontent.com/23097199/122826725-1c68f280-d301-11eb-9c0f-464253b29052.gif)

2021-06-22 09:08 UTC, daemon1024 commented on js/tab-manager.js
> +        .catch((err) => console.debug(err));
Just wondering if we can refactor it into a generic function, since a similar thing is being performed in the the other function.

2021-06-22 09:08 UTC, daemon1024 commented
Rest LGTM 🚀

2021-06-22 14:22 UTC, akshgpt7 commented
The working looks pretty slick. I'm only thinking where can we tell the users about the keyboard shortcuts?
I think we should also have an explicit button in a dropdown (or right-click menu) for restoring in new window (as also discussed in the issue).

2021-06-22 16:42 UTC, PrimalPimmy commented
I think a right click drop down menu would be better along with this.

2021-06-22 16:53 UTC, akshgpt7 commented
Yes, that sounds good till we have enough options to make a collapsible menu button.

2021-06-22 16:55 UTC, daemon1024 commented
Let's consider context menu into a separate PR maybe? If it's a major change? I'm not sure how complicated it's gonna be

2021-06-22 17:26 UTC, PrimalPimmy commented on js/tab-manager.js
> +        .catch((err) => console.debug(err));
Yeah, done. I'll make a commit.

2021-06-22 17:44 UTC, daemon1024 requested changes
Small Nit.

2021-06-22 17:44 UTC, daemon1024 commented on js/tab-manager.js
> +    console.log(`Error: ${error}`);
```suggestion
    console.debug(`Error: ${error}`);
```
Since that's how it's been for all the other cases.

2021-06-23 06:24 UTC, daemon1024 approved these changes
Noicee 🎉

2021-06-24 08:34 UTC, merged