few minor ui changes
osdc/TabuRei pull request #78
Opened 2021-12-23 12:29 UTC by aryanploxxx

Made UI changes in the following:
- added a border radius to container and buttons to make them pleasant to eyes.
- added a hover effect to buttons.
- changed font size of heading in pop-up.
- few layout changes in home page (index.html)

![image](https://user-images.githubusercontent.com/94754702/147240727-2f40f063-46fa-4ade-bb5a-88975547aed6.png)

2021-12-23 16:41 UTC, daemon1024 requested changes
Thanks a lot for this Pull Request and taking the effort to improve the UI 🚀 
Left some queries and comments.
Also, I am not really in favor of changing our boxy design to rounded box but open to opinions if the rest think otherwise

2021-12-23 16:41 UTC, daemon1024 commented on index.html
> +      <!-- <h1 class="heading">TabuRei</h1>
Can we remove this code in entirety!

2021-12-23 16:41 UTC, daemon1024 commented on index.html
> +    </div>  <!--container div closed-->
Comment is irrelevant :)

2021-12-23 16:41 UTC, daemon1024 commented on popup.html
> +        <!-- Given size of 2.5rem was tooo big for a pop-up, so reduced it. -->
Please use commit description for explaining the changes rather than like this. 
https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/

2021-12-23 16:41 UTC, daemon1024 commented on index.html
> +        <label id="warning" for="delete">* Warning: This will clear all tabs </label>
Nice 👌🏽

2021-12-23 16:41 UTC, daemon1024 commented on index.html
> +      <!-- <h1 class="heading">TabuRei</h1>
Also any particular reason we switched from the current code to Table?
If possible would like to avoid it since it doesn't seem semantically right.

2021-12-23 16:41 UTC, daemon1024 commented on css/style.css
> +button:hover {
nice

2021-12-23 16:41 UTC, daemon1024 commented on css/style.css
> +  text-decoration-color: red;
relevance?

2021-12-23 16:46 UTC, akshgpt7 reviewed
These changes look good.
I personally kinda like the curved boxes, if you also make the buttons similar maybe?
That'll make it look more consistent.

2021-12-23 16:47 UTC, aryanploxxx commented on css/style.css
> +  text-decoration-color: red;
Nothing, I forgot to remove it.

2021-12-23 16:48 UTC, aryanploxxx commented
> These changes look good. I personally kinda like the curved boxes, if you also make the buttons similar maybe? That'll make it look more consistent.

I have added a 3px border-radius to the buttons, I can increase it if you like it that way.

2021-12-24 05:24 UTC, daemon1024 commented on index.html
> +      <div id="group-list" style="">
why the need to set empty style?

2021-12-24 06:13 UTC, aryanploxxx commented on index.html
> +      <div id="group-list" style="">
removed.

2021-12-24 06:20 UTC, daemon1024 approved these changes
LGTM! Can you share screenshots again before we merge this :)
Thank You

2021-12-24 06:22 UTC, aryanploxxx commented
![image](https://user-images.githubusercontent.com/94754702/147324354-6c125337-3c03-4fd0-b2db-0db291042669.png)

2021-12-24 06:47 UTC, aryanploxxx commented
![image](https://user-images.githubusercontent.com/94754702/147326166-62335792-b1fd-4639-b060-15b8fb680f98.png)

2021-12-24 06:48 UTC, merged